name: viacep
description: An app of ViaCEP API use.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluentui_system_icons: ^1.1.217
  google_fonts: ^6.1.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  http: ^1.1.0
  pinput: ^3.0.1
  flutter_slidable: ^3.0.0
  flutter_dotenv: ^5.1.0
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
